import { useEffect, useState } from "react";
import { api } from "../lib/api";
import type { UserRecord } from "../types";
export function Users() {
  const [query, setQuery] = useState(""); const [users, setUsers] = useState<UserRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const search = async (value = query) => { setLoading(true); setError(""); try { const result = await api.users.search(value, 50); setUsers(result.users || []); } catch (e) { setError(e instanceof Error ? e.message : "Could not load users."); } finally { setLoading(false); } };
  useEffect(() => { void search(""); }, []);
  return <div className="neo-page"><section className="neo-section-heading"><div><span className="neo-kicker">Audience</span><h2>Users</h2><p>Identity users who have consented to one of your applications. No cross-tenant user browsing.</p></div><span className="neo-status-pill">{users.length} shown</span></section><section className="neo-panel"><form className="neo-users-search" onSubmit={(e) => { e.preventDefault(); void search(); }}><input value={query} onChange={(e) => setQuery(e.target.value)} maxLength={120} placeholder="Search email, username, name, or ID" aria-label="Search authorized users"/><button className="neo-button neo-button-primary" disabled={loading}>{loading ? "Searching…" : "Search users"}</button></form>{error && <div className="neo-form-error" role="alert">{error} <button className="neo-button neo-button-secondary" onClick={() => void search()}>Retry</button></div>}{loading ? <div className="neo-state"><span className="neo-spinner"/><strong>Loading authorized users</strong></div> : users.length ? <div className="neo-user-table">{users.map((user) => <article key={user.id} className="neo-user-row"><span className="neo-avatar">{(user.display_name || user.username || user.email || "U").charAt(0).toUpperCase()}</span><div className="neo-user-identity"><strong>{user.display_name || user.username || "Unnamed user"}</strong><span>{user.email || user.username || user.id}</span><small>{user.email_verified ? "Email verified" : "Email not verified"} · Joined {new Date(user.created_at).toLocaleDateString()}</small></div><div className="neo-user-flags">{user.frozen_at ? <span className="neo-status-pill is-revoked">Frozen</span> : <span className="neo-status-pill">Active</span>}{user.onboarding_completed_at && <span className="neo-status-pill">Onboarded</span>}</div></article>)}</div> : <div className="neo-state"><strong>No authorized users found</strong><span>Users appear after they consent to an application you own.</span></div>}</section></div>;
}
